[build]
  command = "yarn workspace @moderator-role/view build"
  publish = "packages/view/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22"
