export enum ScenarioEntryType {
    MODERATOR_ADMIT = 'MODERATOR_ADMIT',
    SELLER_ADMIT = 'SELLER_ADMIT',
    MODERATOR_DEFEND = 'MODERATOR_DEFEND',
    SELLER_DEFEND = 'SELLER_DEFEND',
    SELLER_IGNORE = 'SELLER_IGNORE',
}
